config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy]
  namespace :admin do
      resources :users
      resources :admin_users
      resources :posts

      root to: "users#index"
    end
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
end

app/views/shared/_nav.html.erb
<div></div>
<% if current_user %>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Overtime Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-link" >
          <%= link_to "Home", root_path %>
        </li>
        <li class="nav-link">
          <%=link_to "Entries", posts_path %>
        </li>
        <li class="nav-link">
          <%=link_to "Add New Entry", new_post_path %>
        </li>
        <% if policy(AuditLog).index? %>
        <li class="nav-link">
          <%=link_to "Audit Logs", audit_logs_path %>
        </li>
        <% end %>
      </ul>
      
      <ul class="dropdown pull-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.full_name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if current_user.try(:type) == 'AdminUser' %>
            <li class="nav-link">
                <%=link_to "Admin Dash", admin_root_path %>
            </li>
            <li class="divider"></li>
            <% end %>
            <li class="nav-link">
                <%=link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
            
          </ul>
        </li>
      </ul>
      

    </div>
  </div>
</nav>
<% end %>